#
# Makefile for org.gjt.sp.jedit.proto package
#
# It runs $(MAKE) for all sub-packages.
#

all: subdirs

subdirs:
	$(MAKE) -f org/gjt/sp/jedit/proto/jeditdocs/Makefile
	$(MAKE) -f org/gjt/sp/jedit/proto/jeditresource/Makefile

include Rules.make
