#
# Makefile for org.gjt.sp.jedit.event package
#
# It compiles files in the above package.
#

classes=org/gjt/sp/jedit/event/AbstractEditorEvent.class \
	org/gjt/sp/jedit/event/BufferAdapter.class \
	org/gjt/sp/jedit/event/BufferEvent.class \
	org/gjt/sp/jedit/event/BufferListener.class \
	org/gjt/sp/jedit/event/EditorAdapter.class \
	org/gjt/sp/jedit/event/EditorEvent.class \
	org/gjt/sp/jedit/event/EditorListener.class \
	org/gjt/sp/jedit/event/EventMulticaster.class \
	org/gjt/sp/jedit/event/ViewAdapter.class \
	org/gjt/sp/jedit/event/ViewEvent.class \
	org/gjt/sp/jedit/event/ViewListener.class

others=

all: $(classes)
	echo $(classes) $(others) >> .resources

include Rules.make
