#!/bin/sh
# Configure script for jEdit

# Functions
error()
{
	rm -f $RULES testmakefile
	exit $1
}

rulesOut()
{
	echo "$@" >&8
}

# Print message
VERSION=1.2final
echo ">> Configuring jEdit $VERSION"
echo

# Trap signals
trap error 1
trap error 2
trap error 3
trap error 15

# Create rules file
RULES=Rules.make
exec 7>/dev/null 8>$RULES
rulesOut "# Created by Configure on `date`"
rulesOut ".SUFFIXES: .java .class"
rulesOut '../$(jar): $(resources)'
rulesOut '	$(JAR) cf0 ../$(jar) $(resources) $(no_compile_res)'
rulesOut ".java.class:"
rulesOut '	@echo $<:'
rulesOut '	@$(JAVAC) -classpath $(CLASSPATH):../.. $<'
rulesOut VERSION=$VERSION

# Configure paths
echo -n "Where do you want to install jEdit? [/opt/slava/share/jedit-$VERSION] "
read JEDIT_HOME
if test "$JEDIT_HOME" = ""
then
	JEDIT_HOME="/opt/slava/share/jedit-$VERSION"
fi

echo -n "Where do you want to install jEdit's shell script? [/opt/slava/bin] "
read JEDIT_BIN
if test "$JEDIT_BIN" = ""
then
	JEDIT_BIN=/opt/slava/bin
fi

rulesOut "JEDIT_HOME=$JEDIT_HOME"
rulesOut "JEDIT_BIN=$JEDIT_BIN"

# Configure java
echo -n "What is the name of your Java virtual machine? [jre] "
read JAVA
if test "$JAVA" = ""
then
	JAVA=jre
fi
rulesOut JAVA=$JAVA

# Configure javac
echo -n "What is the name of your Java compiler? [javac] "
read JAVAC
if test "$JAVAC" = ""
then
	JAVAC=javac
fi
rulesOut JAVAC=$JAVAC

# Configure jar
echo -n "What is the name of your JAR tool? [jar] "
read JAR
if test "$JAR" = ""
then
	JAR=jar
fi
rulesOut JAR=$JAR

# Configure KDE
echo -n "Are you running the K Desktop Enviroment? [yN] "
read KDE
case $KDE in
	y*|Y*)
		echo -n ">> Where is KDE located? [/opt/kde] "
		read KDE_DIR
		if test "$KDE_DIR" = ""
		then
			KDE_DIR=/opt/kde
		fi ;;
esac

rulesOut KDE_DIR=$KDE_DIR

# Some makes don't set $MAKE
echo 'all:' > testmakefile
echo '	@echo $(MAKE)' >> testmakefile
test "`make -f testmakefile`" = "" && rulesOut MAKE=make
rm -f testmakefile

# Set Java VM
cp jedit jedit.cf_tmp
sed "s/JAVA=.*/JAVA=\"$JAVA\"/g" < jedit.cf_tmp > jedit
chmod +x jedit
rm -f jedit.cf_tmp

echo
echo ">> Configuration complete."
echo ">> Run 'make install' to install jEdit."
echo ">> Run 'make' if you wish to recompile it first."
echo
