#!/bin/sh

# Script for starting jEdit on Unix, (c) 1999 Slava Pestov

# The following enviroment variables can be used to customize
# this script:
#
# JAVA - the java virtual machine (default is java)
# JEDIT_HOME - the directory where jedit.jar is stored (default is directory
# of this script, after any links have been followed)
# JEDIT_RMI - the name jEdit will register itself under in the RMI registry
# (default is org.gjt.sp.jedit/RemoteEditor/`whoami`-$DISPLAY)
# JEDIT - additional settings to pass to Java virtual machine (e.g., -mx32m)
#
# These are in addition to the ones supported by the Java VM
# (CLASSPATH, THREADS_FLAG, etc)

# Hook for configure script's Java virtual machine setting
test "$JAVA" = "" && JAVA="java"

# Find full path of $0 (the shell script)
case $0 in
	# Absolute path, use with no modifications
	/*) PRG=$0 ;;
	# Relative path, stick current directory on
	./*) PRG=`pwd`/$0 ;;
	# A program name, should be in PATH
	*) PRG=`which $0` ;;
esac

# User can specify jEdit's home directory manually
if test "$JEDIT_HOME" = ""
then
	# Follow symbolic links, if any (/usr/local/bin/jedit
	# is usually a link to /usr/local/share/jedit-<version>/jedit)
	while test -h "$PRG"
	do
		PRG=`ls -l "$PRG" | sed 's/.*-> //'`
	done
	JEDIT_HOME="`dirname $PRG`"
fi

# Create classpath command. JRE supports -cp option to
# append to classpath, Java does not. (This restriction
# was lifted with Java 2, where -classpath does the same
# as -cp)
if test `basename "$JAVA"` = "jre"
then
	cp="-cp $JEDIT_HOME/jedit.jar"
else
	cp="-classpath $CLASSPATH:$JEDIT_HOME/jedit.jar"
fi

# Construct the -rmi= parameter from $DISPLAY and `whoami`
# if the user hasn't specified it manually
if test "$JEDIT_RMI" = ""
then
	JEDIT_RMI=org.gjt.sp.jedit/RemoteEditor/`whoami`-`echo $DISPLAY|sed -e 's/\..*//g'`
fi

# Construct the command line

# $JEDIT enviroment variable can be set to any additional
# virtual machine settings (larger memory size, etc)
CMDLINE="$JAVA -Djava.rmi.server.codebase=file://$JEDIT_HOME/ \
	$JEDIT $cp org.gjt.sp.jedit.jEdit -rmi=$JEDIT_RMI"

# Finally, start jEdit
$CMDLINE $@
