#
# Makefile for org.gjt.sp.jedit.search package
#
# It compiles files in the above package.
#

classes=org/gjt/sp/jedit/search/AllBufferSet.class \
	org/gjt/sp/jedit/search/BufferListSet.class \
	org/gjt/sp/jedit/search/CurrentBufferSet.class \
	org/gjt/sp/jedit/search/LiteralSearchMatcher.class \
	org/gjt/sp/jedit/search/RESearchMatcher.class \
	org/gjt/sp/jedit/search/SearchAndReplace.class \
	org/gjt/sp/jedit/search/SearchFileSet.class \
	org/gjt/sp/jedit/search/SearchMatcher.class

others=

all: $(classes)
	echo $(classes) $(others) >> .resources

include Rules.make
