#
# Makefile for org.gjt.sp.jedit.gui package
#
# It compiles files in the above package.
#

classes=org/gjt/sp/jedit/gui/BufferOptions.class \
	org/gjt/sp/jedit/gui/ClippingEditor.class \
	org/gjt/sp/jedit/gui/EnhancedMenuItem.class \
	org/gjt/sp/jedit/gui/GlobalOptions.class \
	org/gjt/sp/jedit/gui/HelpViewer.class \
	org/gjt/sp/jedit/gui/HistoryModel.class \
	org/gjt/sp/jedit/gui/HistoryTextField.class \
	org/gjt/sp/jedit/gui/HyperSearch.class \
	org/gjt/sp/jedit/gui/MultiFileSearchDialog.class \
	org/gjt/sp/jedit/gui/OptionsDialog.class \
	org/gjt/sp/jedit/gui/PastePredefined.class \
	org/gjt/sp/jedit/gui/PastePrevious.class \
	org/gjt/sp/jedit/gui/PluginOptions.class \
	org/gjt/sp/jedit/gui/SearchDialog.class \
	org/gjt/sp/jedit/gui/SelectLineRange.class \
	org/gjt/sp/jedit/gui/SendDialog.class \
	org/gjt/sp/jedit/gui/SplashScreen.class \
	org/gjt/sp/jedit/gui/ViewRegisters.class

others='org/gjt/sp/jedit/gui/BufferOptions$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/BufferOptions$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/HelpViewer$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/HelpViewer$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/HelpViewer$$LinkHandler.class' \
	'org/gjt/sp/jedit/gui/HistoryTextField$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/HistoryTextField$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/HistoryTextField$$MouseHandler.class' \
	'org/gjt/sp/jedit/gui/HyperSearch$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/HyperSearch$$EditorHandler.class' \
	'org/gjt/sp/jedit/gui/HyperSearch$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/HyperSearch$$ListHandler.class' \
	'org/gjt/sp/jedit/gui/HyperSearch$$SearchResult.class' \
	'org/gjt/sp/jedit/gui/MultiFileSearchDialog$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/MultiFileSearchDialog$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/PastePrevious$$1.class' \
	'org/gjt/sp/jedit/gui/SearchDialog$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/SearchDialog$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/ViewRegisters$$ActionHandler.class' \
	'org/gjt/sp/jedit/gui/ViewRegisters$$KeyHandler.class' \
	'org/gjt/sp/jedit/gui/ViewRegisters$$MouseHandler.class'

all: $(classes)
	echo $(classes) $(others) >> .resources

include Rules.make
