cd HelloWorld
call makeit.bat
cd ..\InsertDate
call makeit.bat
cd ..\Reverse
call makeit.bat
cd ..\Send
call makeit.bat
cd ..\ToLower
call makeit.bat
cd ..\ToUpper
call makeit.bat
cd ..\WordCount
call makeit.bat
