# Makefile
# Version: 1.0

all:
	$(MAKE) -C HelloWorld
	$(MAKE) -C InsertDate
	$(MAKE) -C Reverse
	$(MAKE) -C Rot13
	$(MAKE) -C Send
	$(MAKE) -C ToLower
	$(MAKE) -C ToUpper
	$(MAKE) -C WordCount
install:
	$(MAKE) -C HelloWorld install
	$(MAKE) -C InsertDate install
	$(MAKE) -C Reverse install
	$(MAKE) -C Rot13 install
	$(MAKE) -C Send install
	$(MAKE) -C ToLower install
	$(MAKE) -C ToUpper install
	$(MAKE) -C WordCount install
