# Makefile
# Version: 1.0

all:
	$(MAKE) -C HelloWorld
	$(MAKE) -C ToUpper
	$(MAKE) -C ToLower
	$(MAKE) -C Reverse
	$(MAKE) -C WordCount
install:
	$(MAKE) -C HelloWorld install
	$(MAKE) -C ToUpper install
	$(MAKE) -C ToLower install
	$(MAKE) -C Reverse install
	$(MAKE) -C WordCount install
