#
# Makefile for org.gjt.sp.jedit.proto.jeditresource package
#
# It compiles files in the above package.
#

classes=org/gjt/sp/jedit/proto/jeditresource/Handler.class \
	org/gjt/sp/jedit/proto/jeditresource/PluginResURLConnection.class

others=

all: $(classes)
	echo $(classes) $(others) >> .resources

include Rules.make
