# Makefile
# Version: 1.0

files=../BUGS ../INSTALL ../README ../TODO ../COPYING commands.txt menus.txt \
	plugins.txt props.txt server.txt
directory=$(SLAVA_DOC_DIR)
all:
install: default-install
include ../Rules.make
