#
# Makefile for doc directory
#
# It creates javadocs for jEdit's core classes
#

all:
	-javadoc -J-mx24m -noindex -notree -d doc/api org.gjt.sp.jedit \
		org.gjt.sp.jedit.event \
		org.gjt.sp.jedit.remote \
		org.gjt.sp.jedit.syntax \
		org.gjt.sp.jedit.textarea

include Rules.make
