#
# Makefile for org.gjt.sp.jedit.mode package
#
# It compiles files in the above package.
#

classes=org/gjt/sp/jedit/mode/bat.class \
	org/gjt/sp/jedit/mode/c.class \
	org/gjt/sp/jedit/mode/cc.class \
	org/gjt/sp/jedit/mode/html.class \
	org/gjt/sp/jedit/mode/idl.class \
	org/gjt/sp/jedit/mode/java_mode.class \
	org/gjt/sp/jedit/mode/javascript.class \
	org/gjt/sp/jedit/mode/makefile.class \
	org/gjt/sp/jedit/mode/patch.class \
	org/gjt/sp/jedit/mode/perl.class \
	org/gjt/sp/jedit/mode/props.class \
	org/gjt/sp/jedit/mode/python.class \
	org/gjt/sp/jedit/mode/sh.class \
	org/gjt/sp/jedit/mode/tex.class \
	org/gjt/sp/jedit/mode/text.class \
	org/gjt/sp/jedit/mode/tsql.class \
	org/gjt/sp/jedit/mode/xml.class

others=

all: $(classes)
	echo $(classes) $(others) >> .resources

include Rules.make
