# Makefile
# Version: 1.0

all:
	@(cd JavaPrettyPrint; $(MAKE))
	@(cd Reverse; $(MAKE))
	@(cd Rot13; $(MAKE))
install:
	@(cd JavaPrettyPrint; $(MAKE) install)
	@(cd Reverse; $(MAKE) install)
	@(cd Rot13; $(MAKE) install)
