
# Makefile for org.gjt.sp.jedit.proto.jeditplugins package
#
# It compiles files in the above package.
#

classes=org/gjt/sp/jedit/proto/jeditdocs/Handler.class \
	org/gjt/sp/jedit/proto/jeditdocs/DocIndexURLConnection.class

others=

all: $(classes)
	echo $(classes) $(others) >> .resources

include Rules.make
