# Makefile
# Version: 1.0

jar=../java_prettyprint.jar
resources=Cmd_java_prettyprint.class JavaPrettyPrintDialog.class \
	jstyle/JSBeautifier.class java_prettyprint.props
all: $(jar)
install: jar-install
include ../../Rules.make
