#!/bin/sh

# simlaunch: Generic script for lauching Java applications
# Part of the SIM (Slava's Installer Maker) package
# (c) 1999 Slava Pestov

# It accepts two or more command line parameters. The first one
# is the name of the application to start, the second is the main
# class, and the rest are passed to the application.

# It does the following to launch the application:
# 1) Locates it in the path
# 2) Traces any symlinks back to its install directory
# 3) Runs the JAR file in the install directory named after the
# application

if test "$1" = "" || test "$1" = "-usage"
then
	echo "Usage: simlaunch <name> <parameters>"
	echo "Report bugs to Slava Pestov <sp@gjt.org>."
	exit 1
fi

if test "$1" = "-version"
then
	echo "SIM launcher version 0.1.1"
	exit 1
fi

test "$JAVA" = "" && JAVA="java"

# Find full path of $1
case $1 in
	# Absolute path, use with no modifications
	/*) PRG=$1 ;;
	# Relative path, stick current directory on
	./*) PRG=`pwd`/$1 ;;
	# A program name, should be in PATH
	*) PRG=`which $1` ;;
esac

# Follow symbolic links, if any
while test -h "$PRG"
do
	PRG=`ls -l "$PRG" | sed 's/.*-> //'`
done

# Create classpath command. JRE supports -cp option to
# append to classpath, Java does not. (This restriction
# was lifted with Java 2, where -classpath does the same
# as -cp)
if test `basename "$JAVA"` = "jre"
then
	cp="-cp $PRG.jar"
else
	cp="-classpath $CLASSPATH:$PRG.jar"
fi

# Get rid of initial parameter
shift 1

# Finally, start the program
exec $JAVA $SIM_SETTINGS $cp $@
