# Makefile
jar=LatestVersion.jar
classes=LatestVersionPlugin.class VersionCheckThread.class \
	version_check_now.class version_check_settings.class
others='LatestVersionPlugin$$EditorHandler.class' LatestVersion.props \
	'VersionCheckThread$$NewVersionAvailable.class' index.html
include ../../Rules.make
