# Makefile
resources=jEdit.class \
	jOpen.class \
	Autosave.class \
	Buffer.class \
	BufferMgr.class \
	Command.class \
	CommandMgr.class \
	Marker.class \
	PropsMgr.class \
	Server.class \
	View.class \
	Cmd_about.class \
	Cmd_clear.class \
	Cmd_clear_marker.class \
	Cmd_close_file.class \
	Cmd_close_view.class \
	Cmd_copy.class \
	Cmd_cut.class \
	Cmd_exit.class \
	Cmd_goto_line.class \
	Cmd_goto_marker.class \
	Cmd_help.class \
	Cmd_new_file.class \
	Cmd_new_view.class \
	Cmd_open_file.class \
	Cmd_open_selection.class \
	Cmd_open_url.class \
	Cmd_paste.class \
	Cmd_print.class \
	Cmd_redo.class \
	Cmd_save.class \
	Cmd_save_as.class \
	Cmd_save_url.class \
	Cmd_select_all.class \
	Cmd_select_buffer.class \
	Cmd_set_marker.class \
	Cmd_undo.class \
	properties
jar=jedit.jar
files=$(jar)
directory=$(SLAVA_SHARE_DIR)
all: $(jar)
install: default-install
properties:
include ../Rules.make
